package testgit4idea.test.test;

/*Generated by MPS */

import testgit4idea.plugin.plugin.TestGit4IdeaCall;

public class Test2 {
  public static void main(String[] args) {
    TestGit4IdeaCall test = new TestGit4IdeaCall();
    test.printName();
  }
}
