package testgit4idea.test.test;

/*Generated by MPS */

import git4idea.commands.GitCommand;

public class Test1 {
  public static void main(String[] args) {
    GitCommand command = GitCommand.CONFIG;
    System.out.println(command.name());
  }
}
