package testgit4idea.testplugin.plugin;

/*Generated by MPS */

import git4idea.DialogManager;
import org.jetbrains.annotations.NotNull;
import com.intellij.openapi.ui.DialogWrapper;
import com.intellij.openapi.project.Project;
import org.jetbrains.annotations.Nullable;
import javax.swing.Icon;

public class TestExtension extends DialogManager {

  @Override
  protected void showDialog(@NotNull DialogWrapper dialog) {
    System.out.println("showDialog(" + dialog + ")");
    super.showDialog(dialog);
  }
  @Override
  protected int showMessageDialog(@NotNull Project project, @NotNull String message, @NotNull String title, @NotNull String[] options, int defaultButtonIndex, @Nullable Icon icon) {
    System.out.println("showMessageDialog[1](" + project + ", " + message + ", " + title + ", options, defaultButtonIndex, icon)");
    return super.showMessageDialog(project, message, title, options, defaultButtonIndex, icon);
  }
  @Override
  protected int showMessageDialog(@NotNull Project project, @NotNull String message, @NotNull String title, @NotNull String[] options, int defaultButtonIndex, int focusedButtonIndex, @Nullable Icon icon) {
    System.out.println("showMessageDialog[2](" + project + ", " + message + ", " + title + ", options, defaultButtonIndes, focusedButtonIndex, icon)");
    return super.showMessageDialog(project, message, title, options, defaultButtonIndex, focusedButtonIndex, icon);
  }
  @Override
  protected int showMessageDialog(@NotNull String description, @NotNull String title, @NotNull String[] options, int defaultButtonIndex, int focusedButtonIndex, @Nullable Icon icon, @Nullable DialogWrapper.DoNotAskOption dontAskOption) {
    System.out.println("showMessageDialog[3](" + description + ", " + title + ", options, defaultButtonIndex, focusedButtonIndex, icon)");
    return super.showMessageDialog(description, title, options, defaultButtonIndex, focusedButtonIndex, icon, dontAskOption);
  }
}
