package testgit4idea.testplugin.plugin;

/*Generated by MPS */

import git4idea.commands.GitCommand;

public class TestPlugin {
  /*package*/ static GitCommand command = GitCommand.CONFIG;
  public static void main(String[] args) {
    System.out.println("TestPlugin: command.name=" + command.name());
  }
}
