package testgit4idea.testplugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.part.ProjectPluginPart;
import jetbrains.mps.project.MPSProject;
import com.intellij.util.messages.MessageBusConnection;
import git4idea.repo.GitRepositoryChangeListener;
import org.jetbrains.annotations.NotNull;
import git4idea.repo.GitRepository;

public class TestSubscription_ProjectPluginPart extends ProjectPluginPart {
  public TestSubscription_ProjectPluginPart() {
  }
  @Override
  public void init(MPSProject project) {
    MessageBusConnection connection = project.getProject().getMessageBus().connect();
    GitRepositoryChangeListener listener = new GitRepositoryChangeListener() {
      @Override
      public void repositoryChanged(@NotNull GitRepository repository) {
        System.out.println("!!!!!!! JUST TESTING !!!!! repo = " + repository);
      }
    };
    connection.subscribe(GitRepository.GIT_REPO_CHANGE, listener);
  }
}
