package testgit4idea.testplugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.projectplugins.BaseProjectPlugin;
import java.util.List;
import jetbrains.mps.plugins.part.ProjectPluginPart;

public class Testplugin_ProjectPlugin extends BaseProjectPlugin {
  public Testplugin_ProjectPlugin() {
  }
  public void fillCustomParts(List<ProjectPluginPart> parts) {
    parts.add(new TestSubscription_ProjectPluginPart());
  }
}
